FROM redhat/ubi8:8.5
MAINTAINER 'Luíza Sabchuk  <luizasabchuk at gmail.com>'
LABEL description="A custom container for the Docker course"
RUN yum install -y httpd && \
    yum clean all
ENV PORT 8080
EXPOSE 80
CMD bash