version: "7.0"
services: 
  web:
    build: .
    ports:
       - "800:5000"
  redis:
    image: redis:7.0
    ports:
       - '6379:6379'
    restart: always
    volumes: 
      - ./cache:/data
volumes:
  cache:
    driver: local
